# This job runs a schema check
name: Schema checks

# It runs for every PR opened, updated and edited
on:
  pull_request:
    types: [opened, synchronize, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_schema:
    name: Run schema checks

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/environments
    environment: apollo

    # https://docs.github.com/en/actions/reference/encrypted-secrets
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
    env:
      APOLLO_KEY: service:peotic-plates:ZR_mZ3lmksIX_hs4r0tB7A
      APOLLO_GRAPH_REF: peotic-plates@current
      APOLLO_SUBGRAPH_NAME: recipes

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Step: Install Rover
      - name: Install Rover
        run: |
          # Install a specific version of Rover, recommended for CI environments to ensure predictable behavior
          curl -sSL https://rover.apollo.dev/nix/v0.13.0 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      # Step: Run schema checks
      - name: Run schema checks
        run: rover subgraph check peotic-plates@current --schema schema.graphql --name recipes
